name: TryHackMe Badge Updater

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download badge image
        run: |
          mkdir -p assets
          curl -o assets/thm_propic.png https://tryhackme-badges.s3.amazonaws.com/Kyubie.png

      - name: Commit and push badge
        run: |
          git config user.name "thm-auto-bot"
          git config user.email "bot@thm.local"
          git add assets/thm_propic.png
          git commit -m "⬆️ Update TryHackMe badge" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
